name: Trigger Repo B Deploy

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch to cros-repo-TINKER
        uses: peter-evans/repository-dispatch@v2
        with:          
          token: ${{ secrets.REMOTE_TRIGGER_PACKAGING }}
          repository: Gauss-Robotics/cros-repo-TINKER
          event-type: do-this
          client-payload: |
            {
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}"
            }
